# Generated by Django 6.0 on 2025-12-10 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="HomeContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=200)),
                ("hero_subtitle", models.CharField(blank=True, max_length=300)),
                ("story_title", models.CharField(blank=True, max_length=200)),
                ("story_paragraph_1", models.TextField(blank=True)),
                ("story_paragraph_2", models.TextField(blank=True)),
                (
                    "story_image",
                    models.ImageField(blank=True, null=True, upload_to="home/story/"),
                ),
                ("cta_title", models.CharField(blank=True, max_length=200)),
                ("cta_text", models.TextField(blank=True)),
                (
                    "cta_image",
                    models.ImageField(blank=True, null=True, upload_to="home/cta/"),
                ),
                (
                    "cta_button_label",
                    models.CharField(
                        blank=True, default="View all Products →", max_length=100
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("price_per_kg", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_best_seller", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        default="9618500442",
                        help_text="WhatsApp number, e.g. 9618500442",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp_message",
                    models.CharField(
                        blank=True,
                        help_text="Pre-filled WhatsApp message. If empty, a default based on product name will be used.",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="nellore_maha_ruchulu_app.category",
                    ),
                ),
            ],
        ),
    ]
