# Generated by Django 6.0 on 2025-12-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nellore_maha_ruchulu_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        blank=True, default="About Nellore Maharuchulu", max_length=200
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("story_title", models.CharField(blank=True, max_length=200)),
                ("story_paragraph_1", models.TextField(blank=True)),
                ("story_paragraph_2", models.TextField(blank=True)),
                (
                    "story_image",
                    models.ImageField(blank=True, null=True, upload_to="about/story/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
