# Generated by Django 6.0 on 2025-12-12 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nellore_maha_ruchulu_app", "0002_aboutcontent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutcontent",
            options={
                "verbose_name": "About Page Content",
                "verbose_name_plural": "About Page Content",
            },
        ),
        migrations.RenameField(
            model_name="aboutcontent",
            old_name="page_title",
            new_name="hero_title",
        ),
        migrations.RenameField(
            model_name="aboutcontent",
            old_name="story_title",
            new_name="story_heading",
        ),
        migrations.RemoveField(
            model_name="aboutcontent",
            name="subtitle",
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="cta_button_label",
            field=models.CharField(
                blank=True, default="View all Products →", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="cta_button_url",
            field=models.CharField(blank=True, default="/products/", max_length=255),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="cta_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="cta_title",
            field=models.CharField(
                blank=True, default="Ready to Taste the Tradition?", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="hero_subtitle",
            field=models.CharField(
                blank=True,
                default="Bringing the flavors of Andhra’s kitchens to your home.",
                max_length=300,
            ),
        ),
        migrations.CreateModel(
            name="WhyCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("paragraph", models.TextField(blank=True)),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="about/icons/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="why_cards",
                        to="nellore_maha_ruchulu_app.aboutcontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Why Card",
                "verbose_name_plural": "Why Cards",
                "ordering": ("order",),
            },
        ),
    ]
