# Generated by Django 6.0 on 2025-12-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nellore_maha_ruchulu_app", "0003_alter_aboutcontent_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(blank=True, default="Contact Us", max_length=200),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        blank=True,
                        default="We’d love to hear from you — whether it’s for orders, feedback, or questions about our products.",
                        max_length=300,
                    ),
                ),
                (
                    "intro_heading",
                    models.CharField(
                        blank=True, default="We’re Just a Message Away", max_length=200
                    ),
                ),
                ("intro_paragraph", models.TextField(blank=True)),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, default="+91 89657 56562", max_length=50
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="info@nelloremaharuchulu.com",
                        max_length=254,
                    ),
                ),
                (
                    "contact_address",
                    models.CharField(
                        blank=True, default="Nellore, Andhra Pradesh", max_length=255
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="contact/"),
                ),
                (
                    "cta_title",
                    models.CharField(
                        blank=True,
                        default="Ready to Taste the Tradition?",
                        max_length=200,
                    ),
                ),
                ("cta_text", models.TextField(blank=True)),
                (
                    "cta_button_label",
                    models.CharField(
                        blank=True, default="View all Products →", max_length=100
                    ),
                ),
                (
                    "cta_button_url",
                    models.CharField(blank=True, default="/products/", max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Page Content",
                "verbose_name_plural": "Contact Page Content",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("handled", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
