# Generated by Django 6.0 on 2025-12-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nellore_maha_ruchulu_app", "0004_contactcontent_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpfulLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="Helpful Links", max_length=150
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Add HTML list items like: <li><a href='/...'>Label</a></li>",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Footer: Helpful Links",
                "verbose_name_plural": "Footer: Helpful Links",
            },
        ),
    ]
