# Generated by Django 6.0 on 2025-12-12 08:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nellore_maha_ruchulu_app", "0005_helpfullinks"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug, e.g. refund-policy",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(
                        blank=True, help_text="HTML content for the help page"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Help Page",
                "verbose_name_plural": "Help Pages",
                "ordering": ("order",),
            },
        ),
        migrations.DeleteModel(
            name="HelpfulLinks",
        ),
    ]
