# Generated by Django 6.0 on 2025-12-13 07:21

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nellore_maha_ruchulu_app", "0006_helppage_delete_helpfullinks"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("refund", "Refund Policy"),
                            ("terms", "Terms & Conditions"),
                            ("privacy", "Privacy Policy"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", tinymce.models.HTMLField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Legal Page",
                "verbose_name_plural": "Legal Pages",
            },
        ),
        migrations.DeleteModel(
            name="HelpPage",
        ),
    ]
