# Generated by Django 6.0 on 2025-12-15 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nellore_maha_ruchulu_app", "0007_legalpage_delete_helppage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterLinkGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Footer Link Group",
                "verbose_name_plural": "Footer Link Groups",
                "ordering": ("order", "title"),
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Nellore Maharuchulu", max_length=100),
                ),
                (
                    "logo_image",
                    models.ImageField(
                        blank=True,
                        help_text="Logo used in Navbar and Footer.",
                        null=True,
                        upload_to="site/",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        default="+91 89657 56562",
                        help_text="Contact number for Navbar/Footer.",
                        max_length=20,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        default="info@nelloremaharuchulu.com",
                        max_length=254,
                    ),
                ),
                (
                    "address_line",
                    models.CharField(
                        blank=True, default="Nellore, Andhra Pradesh", max_length=150
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="All Rights reserved Lagran.in", max_length=200
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings (Navbar/Footer)",
                "verbose_name_plural": "Site Settings (Navbar/Footer)",
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                (
                    "url",
                    models.CharField(
                        help_text="The URL path (e.g., /products/ or a Django URL name)",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="nellore_maha_ruchulu_app.footerlinkgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Link",
                "verbose_name_plural": "Footer Links",
                "ordering": ("order", "text"),
            },
        ),
    ]
