# Generated by Django 6.0 on 2025-12-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nellore_maha_ruchulu_app", "0008_footerlinkgroup_sitesettings_footerlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductsPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        blank=True, default="Explore Our Products", max_length=200
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        blank=True,
                        default="Discover everything we make with care, love, and authentic Andhra taste.",
                        max_length=300,
                    ),
                ),
                (
                    "sidebar_heading",
                    models.CharField(blank=True, default="Categories", max_length=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Products Page Content",
                "verbose_name_plural": "Products Page Content",
            },
        ),
    ]
