# Generated by Django 6.0 on 2025-12-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nellore_maha_ruchulu_app", "0009_productspagecontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutcontent",
            name="why_choose_subtitle",
            field=models.TextField(
                blank=True,
                default="At Nellore Maharuchulu, we don’t just make food — we preserve tradition. Every item is prepared with care, just like it’s done in Andhra homes. Here’s what makes us special:",
            ),
        ),
        migrations.AddField(
            model_name="aboutcontent",
            name="why_choose_title",
            field=models.CharField(blank=True, default="Why Choose Us", max_length=200),
        ),
        migrations.AddField(
            model_name="contactcontent",
            name="bestseller_subtitle",
            field=models.TextField(
                blank=True,
                default="Tried, loved, and reordered — top picks customers can’t get enough of.",
            ),
        ),
        migrations.AddField(
            model_name="contactcontent",
            name="bestseller_title",
            field=models.CharField(
                blank=True, default="Our Best Sellers", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="homecontent",
            name="bestseller_subtitle",
            field=models.TextField(
                blank=True,
                default="Tried, loved, and reordered. Here are the top picks our customers can’t get enough of.",
            ),
        ),
        migrations.AddField(
            model_name="homecontent",
            name="bestseller_title",
            field=models.CharField(
                blank=True, default="Our Best Sellers", max_length=200
            ),
        ),
    ]
