# Generated by Django 6.0 on 2025-12-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nellore_maha_ruchulu_app", "0010_aboutcontent_why_choose_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecontent",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to="home/hero/"),
        ),
    ]
